// Stardew Valley inspired pixel art sprites for city view
// Each sprite is 16x16 pixels with warm, cozy colors

export type SpriteData = string[][];

export const SPRITE_COLORS_16BIT = {
  // Base colors - warm and inviting
  BLACK: '#1a1a1a',
  WHITE: '#fef3c7',
  GRAY_DARKEST: '#292524',
  GRAY_DARKER: '#44403c',
  GRAY_DARK: '#57534e',
  GRAY_MID: '#78716c',
  GRAY_LIGHT: '#a8a29e',
  GRAY_LIGHTER: '#d6d3d1',
  GRAY_LIGHTEST: '#f5f5f4',
  
  // Downtown - Blue glass buildings with warm accents
  DOWNTOWN_GLASS: '#60a5fa',
  DOWNTOWN_GLASS_DARK: '#3b82f6',
  DOWNTOWN_GLASS_LIGHT: '#93c5fd',
  DOWNTOWN_STEEL: '#64748b',
  DOWNTOWN_STEEL_DARK: '#475569',
  DOWNTOWN_STEEL_LIGHT: '#94a3b8',
  DOWNTOWN_NEON: '#fbbf24',
  
  // Warehouse - Warm red brick buildings
  WAREHOUSE_BRICK: '#dc2626',
  WAREHOUSE_BRICK_DARK: '#991b1b',
  WAREHOUSE_BRICK_LIGHT: '#ef4444',
  WAREHOUSE_RUST: '#ea580c',
  WAREHOUSE_RUST_DARK: '#c2410c',
  WAREHOUSE_METAL: '#6b7280',
  WAREHOUSE_GRAFFITI: '#ec4899',
  
  // College - Cozy stone buildings with green
  COLLEGE_STONE: '#a8a29e',
  COLLEGE_STONE_DARK: '#78716c',
  COLLEGE_STONE_LIGHT: '#e7e5e4',
  COLLEGE_IVY: '#22c55e',
  COLLEGE_IVY_DARK: '#16a34a',
  COLLEGE_IVY_LIGHT: '#4ade80',
  COLLEGE_POSTER: '#fbbf24',
  
  // Residential - Pastel houses
  RESIDENTIAL_SIDING: '#fca5a5',
  RESIDENTIAL_SIDING_DARK: '#f87171',
  RESIDENTIAL_SIDING_LIGHT: '#fecaca',
  RESIDENTIAL_ROOF: '#7f1d1d',
  RESIDENTIAL_ROOF_DARK: '#450a0a',
  RESIDENTIAL_ACCENT: '#86efac',
  
  // Arts - Bright creative colors
  ARTS_PURPLE: '#c084fc',
  ARTS_PURPLE_DARK: '#a855f7',
  ARTS_PURPLE_LIGHT: '#e9d5ff',
  ARTS_PINK: '#f9a8d4',
  ARTS_PINK_DARK: '#ec4899',
  ARTS_TEAL: '#5eead4',
  ARTS_ORANGE: '#fdba74',
  
  // Special colors - warm lighting
  WINDOW_YELLOW: '#fef08a',
  WINDOW_DARK: '#78716c',
  WINDOW_BLUE: '#bfdbfe',
  NEON_PURPLE: '#e879f9',
  NEON_CYAN: '#67e8f9',
  NEON_PINK: '#fbcfe8',
  NEON_GREEN: '#bbf7d0',
  
  // Nature - lush greens
  GRASS_GREEN: '#4ade80',
  GRASS_DARK: '#22c55e',
  TREE_GREEN: '#16a34a',
  TREE_TRUNK: '#713f12',
  
  // Streets - soft gray paths
  ASPHALT: '#374151',
  ASPHALT_DARK: '#1f2937',
  STREET_LINE: '#fde047',
  SIDEWALK: '#9ca3af',
  SIDEWALK_CRACK: '#6b7280',
  
  TRANSPARENT: 'transparent'
};

// Simple, charming building sprites in Stardew Valley style
const BUILDING_PATTERNS_16BIT = {
  downtown: [
    '................',
    '....DDDDDDDD....',
    '...DDGGGGGGDD...',
    '..DGGLLLLLLGGD..',
    '..DGLLWWWWLLGD..',
    '..DGLLLLLLLLGD..',
    '..DGLLWWWWLLGD..',
    '..DGLLLLLLLLGD..',
    '..DGLLWWWWLLGD..',
    '..DGLLLLLLLLGD..',
    '..DGLLWWWWLLGD..',
    '..DGGGGGGGGGGGD.',
    '..DDDDNDNDDDDD..',
    '..DDDDDDDDDDDD..',
    '................',
    'SSSSSSSSSSSSSSSS'
  ],
  warehouse: [
    '................',
    '..DDDDDDDDDDDD..',
    '.DRRRRRRRRRRRRRD.',
    '.DRBBBBBBBBBBRD.',
    '.DRBWWBWWBWWBRD.',
    '.DRBBBBBBBBBBBRD.',
    '.DRGGGGGGGGGGRD.',
    '.DRBWWBWWBWWBRD.',
    '.DRBBBBBBBBBBBRD.',
    '.DRBBBBBBBBBBBRD.',
    '.DRBWWBWWBWWBRD.',
    '.DRBBBBBBBBBBBRD.',
    '.DRRRMDDDMRRRRD.',
    '.DDDDDDDDDDDDDD.',
    '................',
    'SSCSSSSSSSSCSSSS'
  ],
  college: [
    '................',
    '....LLLLLLLL....',
    '...LLSSSSSSLL...',
    '..LSSIIIIIISSSL.',
    '..LSWWSSWWSWSSL.',
    '..LSSSSSSSSSSSSL.',
    '..LSWWSSWWSWSSL.',
    '..LSSSSSSSSSSSSL.',
    '..LSWWSSWWSWSSL.',
    '..LSSSSSSSSSSSSL.',
    '..LSWWSSWWSWSSL.',
    '..LSSSSSSSSSSSSL.',
    '..LLLDDDDDDDLLL.',
    '..GGGGIGIGGGGG..',
    '................',
    'SSSSSSSSSSSSSSSS'
  ],
  residential: [
    '................',
    '.....RRRRRR.....',
    '....RRRRRRRR....',
    '...RRDDDDDDRR...',
    '..RRDDDDDDDDRR..',
    '..LLLLLLLLLLLL..',
    '..LWWLWWLWWLWL..',
    '..LLLLLLLLLLLL..',
    '..LWWLWWLWWLWL..',
    '..LLLLLLLLLLLL..',
    '..LLLLLDDDLLLL..',
    '..LLLLDAAADLLL..',
    '..GGGGGGGGGGGG..',
    '..GAGAGGGAGAGA..',
    '................',
    'SSSSSSSSSSSSSSSS'
  ],
  arts: [
    '................',
    '....PPPPPPPP....',
    '...PPDDDDDDDP...',
    '..PPTTTTTTTTTP..',
    '..PPOCCCCCCOPP..',
    '..PPTTTTTTTTPP..',
    '..PPWWWWWWWWPP..',
    '..PPTTTTTTTTPP..',
    '..PPWWWWWWWWPP..',
    '..PPTTTTTTTTPP..',
    '..PPWWWWWWWWPP..',
    '..PPDDDDDDDDPP..',
    '..PPPPOOOOOPPP..',
    '..LLLLLLLLLLLL..',
    '................',
    'SSCSSSSSSSSCSSSS'
  ]
};

// Color mappings for buildings with enhanced detail
const BUILDING_COLORS_16BIT = {
  downtown: {
    '.': SPRITE_COLORS_16BIT.TRANSPARENT,
    'S': SPRITE_COLORS_16BIT.DOWNTOWN_STEEL,
    'D': SPRITE_COLORS_16BIT.DOWNTOWN_STEEL_DARK,
    'G': SPRITE_COLORS_16BIT.DOWNTOWN_GLASS,
    'B': SPRITE_COLORS_16BIT.DOWNTOWN_GLASS_DARK,
    'L': SPRITE_COLORS_16BIT.DOWNTOWN_GLASS_LIGHT,
    'N': SPRITE_COLORS_16BIT.DOWNTOWN_NEON,
    'W': SPRITE_COLORS_16BIT.WINDOW_DARK
  },
  warehouse: {
    'B': SPRITE_COLORS_16BIT.WAREHOUSE_BRICK,
    'D': SPRITE_COLORS_16BIT.WAREHOUSE_BRICK_DARK,
    'R': SPRITE_COLORS_16BIT.WAREHOUSE_BRICK_LIGHT,
    'M': SPRITE_COLORS_16BIT.WAREHOUSE_METAL,
    'W': SPRITE_COLORS_16BIT.GRAY_DARK,
    'S': SPRITE_COLORS_16BIT.SIDEWALK,
    'C': SPRITE_COLORS_16BIT.SIDEWALK_CRACK,
    'G': SPRITE_COLORS_16BIT.WAREHOUSE_GRAFFITI
  },
  college: {
    '.': SPRITE_COLORS_16BIT.TRANSPARENT,
    'S': SPRITE_COLORS_16BIT.COLLEGE_STONE,
    'D': SPRITE_COLORS_16BIT.COLLEGE_STONE_DARK,
    'L': SPRITE_COLORS_16BIT.COLLEGE_STONE_LIGHT,
    'I': SPRITE_COLORS_16BIT.COLLEGE_IVY,
    'G': SPRITE_COLORS_16BIT.COLLEGE_IVY_DARK,
    'W': SPRITE_COLORS_16BIT.WINDOW_BLUE,
    'P': SPRITE_COLORS_16BIT.COLLEGE_POSTER
  },
  residential: {
    '.': SPRITE_COLORS_16BIT.TRANSPARENT,
    'S': SPRITE_COLORS_16BIT.RESIDENTIAL_SIDING,
    'D': SPRITE_COLORS_16BIT.RESIDENTIAL_SIDING_DARK,
    'L': SPRITE_COLORS_16BIT.RESIDENTIAL_SIDING_LIGHT,
    'R': SPRITE_COLORS_16BIT.RESIDENTIAL_ROOF,
    'W': SPRITE_COLORS_16BIT.WINDOW_YELLOW,
    'G': SPRITE_COLORS_16BIT.GRASS_GREEN,
    'A': SPRITE_COLORS_16BIT.RESIDENTIAL_ACCENT
  },
  arts: {
    '.': SPRITE_COLORS_16BIT.TRANSPARENT,
    'P': SPRITE_COLORS_16BIT.ARTS_PURPLE,
    'D': SPRITE_COLORS_16BIT.ARTS_PURPLE_DARK,
    'T': SPRITE_COLORS_16BIT.ARTS_TEAL,
    'C': SPRITE_COLORS_16BIT.ARTS_PINK,
    'W': SPRITE_COLORS_16BIT.WINDOW_BLUE,
    'L': SPRITE_COLORS_16BIT.ARTS_PURPLE_LIGHT,
    'O': SPRITE_COLORS_16BIT.ARTS_ORANGE,
    'S': SPRITE_COLORS_16BIT.SIDEWALK
  }
};

// Venue sprite - Cozy underground music club
const VENUE_PATTERN_16BIT = [
  '................',
  '..DDDDDDDDDDDD..',
  '.DRRRRRRRRRRRRRD.',
  '.DRPPPPPPPPPPRD.',
  '.DRPNNNNNNNNPRD.',
  '.DRPPPPPPPPPPRD.',
  '.DRBWWBWWBWWBRD.',
  '.DRBBBGGGBBBBRD.',
  '.DRBWWBWWBWWBRD.',
  '.DRBBBBBBBBBBBRD.',
  '.DRBWWBWWBWWBRD.',
  '.DRBBDDDDDDBBRD.',
  '.DRRRRRRRRRRRRD.',
  '.DDDDDDDDDDDDDD.',
  '................',
  'SSCSSSSSSSSCSSSS'
];

const VENUE_COLORS_16BIT = {
  '.': SPRITE_COLORS_16BIT.TRANSPARENT,
  'D': SPRITE_COLORS_16BIT.GRAY_DARKER,
  'M': SPRITE_COLORS_16BIT.GRAY_DARKEST,
  'B': SPRITE_COLORS_16BIT.WAREHOUSE_BRICK_DARK,
  'P': SPRITE_COLORS_16BIT.NEON_PINK,
  'C': SPRITE_COLORS_16BIT.ARTS_PINK,
  'N': SPRITE_COLORS_16BIT.NEON_PURPLE,
  'W': SPRITE_COLORS_16BIT.WINDOW_DARK,
  'G': SPRITE_COLORS_16BIT.WAREHOUSE_GRAFFITI,
  'S': SPRITE_COLORS_16BIT.SIDEWALK
};

// Workplace - Friendly office building
const WORKPLACE_PATTERN_16BIT = [
  '................',
  '...SSSSSSSSSS...',
  '..SDDDDDDDDDDDS.',
  '..SGGGGGGGGGGGS.',
  '..SGCCCCCCCCCGS.',
  '..SGGGGGGGGGGGS.',
  '..SGCCCCCCCCCGS.',
  '..SGGGGGGGGGGGS.',
  '..SGCCCCCCCCCGS.',
  '..SGGGGGGGGGGGS.',
  '..SGCCCCCCCCCGS.',
  '..SGGGGGGGGGGGS.',
  '..SDDLDDDDDLDDDS.',
  '..SSSSSSSSSSSSS.',
  '................',
  'SSSSSSSSSSSSSSSS'
];

const WORKPLACE_COLORS_16BIT = {
  '.': SPRITE_COLORS_16BIT.TRANSPARENT,
  'M': SPRITE_COLORS_16BIT.DOWNTOWN_STEEL_DARK,
  'S': SPRITE_COLORS_16BIT.DOWNTOWN_STEEL,
  'G': SPRITE_COLORS_16BIT.DOWNTOWN_GLASS,
  'C': SPRITE_COLORS_16BIT.DOWNTOWN_GLASS_LIGHT,
  'L': SPRITE_COLORS_16BIT.DOWNTOWN_STEEL_LIGHT,
  'D': SPRITE_COLORS_16BIT.GRAY_DARKEST
};

// Park with trees and benches - cozy town square feel
const PARK_PATTERN_16BIT = [
  'GGGGGGGGGGGGGGGG',
  'GDTTGGGGGGGGTTDG',
  'GTTTGGPPPPGGTTTG',
  'GTTTTGPBBPGTTTGG',
  'GGBTGGPPPPGGBTGG',
  'GGGGPPPPPPPPGGGG',
  'GGPPPPPPPPPPPPGG',
  'GGPPBBPPPPBBPPGG',
  'GGPPPPPPPPPPPPGG',
  'GGGGPPPPPPPPGGGG',
  'GDTTGGGGGGGGTTDG',
  'GTTTGGAAAAGTTTGG',
  'GGBTGGAAAAGGBTGG',
  'GGGGGGGGGGGGGGGG',
  'GGDGGGGGGGGGGDGG',
  'GGGGGGGGGGGGGGGG'
];

const PARK_COLORS_16BIT = {
  'G': SPRITE_COLORS_16BIT.GRASS_GREEN,
  'D': SPRITE_COLORS_16BIT.GRASS_DARK,
  'T': SPRITE_COLORS_16BIT.TREE_GREEN,
  'B': SPRITE_COLORS_16BIT.TREE_TRUNK,
  'P': SPRITE_COLORS_16BIT.SIDEWALK,
  'A': SPRITE_COLORS_16BIT.ARTS_PINK
};

// Street patterns - clean and simple
const STREET_PATTERNS_16BIT = {
  horizontal: [
    'SSSSSSSSSSSSSSSS',
    'SSSSSSSSSSSSSSSS',
    'SSSSSSSSSSSSSSSS',
    'AAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAA',
    'LLLLLLLLLLLLLLLL',
    'LLLLLLLLLLLLLLLL',
    'AAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAA',
    'SSSSSSSSSSSSSSSS',
    'SSSSSSSSSSSSSSSS',
    'SSSSSSSSSSSSSSSS'
  ],
  vertical: [
    'SSSAAAAAAAAASSS',
    'SSSAAAAAAAAASSS',
    'SSSAAAAAAAAASSS',
    'SSSAAALLLAAASSS',
    'SSSAAALLLAAASSS',
    'SSSAAAAAAAAASSS',
    'SSSAAAAAAAAASSS',
    'SSSAAAAAAAAASSS',
    'SSSAAAAAAAAASSS',
    'SSSAAAAAAAAASSS',
    'SSSAAAAAAAAASSS',
    'SSSAAALLLAAASSS',
    'SSSAAALLLAAASSS',
    'SSSAAAAAAAAASSS',
    'SSSAAAAAAAAASSS',
    'SSSAAAAAAAAASSS'
  ],
  intersection: [
    'SSSAAAAAAAAASSS',
    'SSSAAAAAAAAASSS',
    'SSSAAAAAAAAASSS',
    'AAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAA',
    'AAALLLLLLLLLLAAA',
    'AAALLLLLLLLLLAAA',
    'AAALLLLLLLLLLAAA',
    'AAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAA',
    'SSSAAAAAAAAASSS',
    'SSSAAAAAAAAASSS',
    'SSSAAAAAAAAASSS',
    'SSSAAAAAAAAASSS'
  ]
};

const STREET_COLORS_16BIT = {
  'A': SPRITE_COLORS_16BIT.ASPHALT,
  'L': SPRITE_COLORS_16BIT.STREET_LINE,
  'S': SPRITE_COLORS_16BIT.SIDEWALK
};

// Convert pattern to sprite data
export function createSprite(pattern: string[], colors: Record<string, string>): SpriteData {
  return pattern.map(row => 
    row.split('').map(char => colors[char] || SPRITE_COLORS_16BIT.TRANSPARENT)
  );
}

// Create sprite cache
export const SPRITES_16BIT = {
  // Buildings
  building_downtown: createSprite(BUILDING_PATTERNS_16BIT.downtown, BUILDING_COLORS_16BIT.downtown),
  building_warehouse: createSprite(BUILDING_PATTERNS_16BIT.warehouse, BUILDING_COLORS_16BIT.warehouse),
  building_college: createSprite(BUILDING_PATTERNS_16BIT.college, BUILDING_COLORS_16BIT.college),
  building_residential: createSprite(BUILDING_PATTERNS_16BIT.residential, BUILDING_COLORS_16BIT.residential),
  building_arts: createSprite(BUILDING_PATTERNS_16BIT.arts, BUILDING_COLORS_16BIT.arts),
  
  // Streets
  street_horizontal: createSprite(STREET_PATTERNS_16BIT.horizontal, STREET_COLORS_16BIT),
  street_vertical: createSprite(STREET_PATTERNS_16BIT.vertical, STREET_COLORS_16BIT),
  street_intersection: createSprite(STREET_PATTERNS_16BIT.intersection, STREET_COLORS_16BIT),
  
  // Special
  venue_inactive: createSprite(VENUE_PATTERN_16BIT, VENUE_COLORS_16BIT),
  venue_active: createSprite(VENUE_PATTERN_16BIT, {
    ...VENUE_COLORS_16BIT,
    'P': SPRITE_COLORS_16BIT.NEON_CYAN,
    'C': SPRITE_COLORS_16BIT.NEON_PINK,
    'N': SPRITE_COLORS_16BIT.NEON_GREEN,
    'W': SPRITE_COLORS_16BIT.WINDOW_YELLOW,
    'G': SPRITE_COLORS_16BIT.NEON_PURPLE
  }),
  workplace: createSprite(WORKPLACE_PATTERN_16BIT, WORKPLACE_COLORS_16BIT),
  park: createSprite(PARK_PATTERN_16BIT, PARK_COLORS_16BIT)
};