// 16-bit style pixel art sprites for the city map
// Each sprite is 16x16 pixels with more detailed shading and colors

export type SpriteData = string[][];

export const SPRITE_COLORS_16BIT = {
  // Base colors with more variety
  BLACK: '#000000',
  WHITE: '#FFFFFF',
  GRAY_DARKEST: '#0A0A0A',
  GRAY_DARKER: '#1A1A1A',
  GRAY_DARK: '#2D2D2D',
  GRAY_MID: '#4A4A4A',
  GRAY_LIGHT: '#6B6B6B',
  GRAY_LIGHTER: '#8C8C8C',
  GRAY_LIGHTEST: '#ADADAD',
  
  // Downtown - Modern glass and steel
  DOWNTOWN_GLASS: '#4A90E2',
  DOWNTOWN_GLASS_DARK: '#357ABD',
  DOWNTOWN_GLASS_LIGHT: '#6BA3E5',
  DOWNTOWN_STEEL: '#5A6C7D',
  DOWNTOWN_STEEL_DARK: '#3E4C5C',
  DOWNTOWN_STEEL_LIGHT: '#7A8B9C',
  
  // Warehouse - Industrial brick and rust
  WAREHOUSE_BRICK: '#A0522D',
  WAREHOUSE_BRICK_DARK: '#8B4513',
  WAREHOUSE_BRICK_LIGHT: '#CD853F',
  WAREHOUSE_RUST: '#B7410E',
  WAREHOUSE_RUST_DARK: '#8B3A00',
  WAREHOUSE_METAL: '#696969',
  
  // College - Ivy covered stone
  COLLEGE_STONE: '#8B7D6B',
  COLLEGE_STONE_DARK: '#6B5D4F',
  COLLEGE_STONE_LIGHT: '#A0968C',
  COLLEGE_IVY: '#228B22',
  COLLEGE_IVY_DARK: '#006400',
  COLLEGE_IVY_LIGHT: '#32CD32',
  
  // Residential - Warm homey colors
  RESIDENTIAL_SIDING: '#F4A460',
  RESIDENTIAL_SIDING_DARK: '#D2691E',
  RESIDENTIAL_SIDING_LIGHT: '#FFDAB9',
  RESIDENTIAL_ROOF: '#8B4513',
  RESIDENTIAL_ROOF_DARK: '#654321',
  
  // Arts - Vibrant creative colors
  ARTS_PURPLE: '#9370DB',
  ARTS_PURPLE_DARK: '#7B68EE',
  ARTS_PURPLE_LIGHT: '#BA55D3',
  ARTS_PINK: '#FF69B4',
  ARTS_PINK_DARK: '#FF1493',
  ARTS_TEAL: '#20B2AA',
  
  // Special colors
  WINDOW_YELLOW: '#FFD700',
  WINDOW_DARK: '#B8860B',
  WINDOW_BLUE: '#87CEEB',
  NEON_PURPLE: '#FF00FF',
  NEON_CYAN: '#00FFFF',
  NEON_PINK: '#FF1493',
  
  // Nature
  GRASS_GREEN: '#228B22',
  GRASS_DARK: '#006400',
  TREE_GREEN: '#2E8B57',
  TREE_TRUNK: '#8B4513',
  
  // Streets
  ASPHALT: '#2C2C2C',
  ASPHALT_DARK: '#1C1C1C',
  STREET_LINE: '#FFD700',
  SIDEWALK: '#A9A9A9',
  
  TRANSPARENT: 'transparent'
};

// 16x16 building sprites with more detail
const BUILDING_PATTERNS_16BIT = {
  downtown: [
    '....SSSSSSSS....',
    '...SSGGGGGGSS...',
    '..SSGGGGGGGGSS..',
    '..SGBGBGBGBGDS..',
    '..SGGGGGGGGGDS..',
    '..SGBGBGBGBGDS..',
    '..SGGGGGGGGGDS..',
    '..SGBGBGBGBGDS..',
    '..SGGGGGGGGGDS..',
    '..SGBGBGBGBGDS..',
    '..SGGGGGGGGGDS..',
    '..SGBGBGBGBGDS..',
    '..SDDDDDDDDDDS..',
    '..SSSSSSSSSSSS..',
    '..DDDDDDDDDDDD..',
    '................'
  ],
  warehouse: [
    'RRRRRRRRRRRRRRRR',
    'RDDDDDDDDDDDDDDR',
    'RBBRBBRBBRBBRBBR',
    'RBBRBBRBBRBBRBBR',
    'RDDDDDDDDDDDDDR',
    'RBBRBBRBBRBBRBBR',
    'RBBRBBRBBRBBRBBR',
    'RMMMMMMMMMMMMMR',
    'RBBRBBRBBRBBRBBR',
    'RBBRBBRBBRBBRBBR',
    'RDDDDDDDDDDDDDR',
    'RWWWWWWWWWWWWWR',
    'RWDDDDWDDDDWDDR',
    'RWWWWWWWWWWWWWR',
    'RRRRRRRRRRRRRRRR',
    'DDDDDDDDDDDDDDDD'
  ],
  college: [
    '....SSSSSSSS....',
    '...SSSSSSSSSS...',
    '..SSIISSSIISSS..',
    '..SSISSISSSSSS..',
    '.SSWWSSWWSSWWSS.',
    '.SSDDSSDDSSDDS..',
    '.SSWWSSWWSSWWSS.',
    '.SSISSISSSISSS..',
    '.SSWWSSWWSSWWSS.',
    '.SSDDSSDDSSDDS..',
    '.SSWWSSWWSSWWSS.',
    '.SSISSISSSISSS..',
    '.SSSDDDDDDDSSS..',
    '.SSSSSSSSSSSS...',
    '..DDDDDDDDDD....',
    '................'
  ],
  residential: [
    '......RRRR......',
    '....RRRRRRRR....',
    '...RDDDDDDDR....',
    '..RDDDDDDDDDR...',
    '..SSSSSSSSSSSS..',
    '..SWWSSWWSSWWS..',
    '..SDDSSDDSSDDS..',
    '..SWWSSWWSSWWS..',
    '..SSSSSSSSSSSS..',
    '..SWWSSWWSSWWS..',
    '..SDDSSDDSSDDS..',
    '..SSSSDDDDSSSS..',
    '..SSSDWWWDSSSS..',
    '..SSSSSSSSSSSS..',
    '..GGGGGGGGGGGG..',
    '................'
  ],
  arts: [
    '.....PPPPPP.....',
    '....PPPPPPPP....',
    '...PPTTTTTTPP...',
    '..PPPTPPPPPTPPP.',
    '..PTPTPPPPPTPTP.',
    '..PPPPWWWWPPPP..',
    '..PTPTWDDWTPTP..',
    '..PPPPWWWWPPPP..',
    '..PTPTPPPPPTPTP.',
    '..PPPPWWWWPPPP..',
    '..PTPTWDDWTPTP..',
    '..PPPPDDDDPPPP..',
    '..PPPPDCCDPPPP..',
    '..PPPPPPPPPPPP..',
    '...DDDDDDDDDD...',
    '................'
  ]
};

// Color mappings for 16-bit buildings
const BUILDING_COLORS_16BIT = {
  downtown: {
    '.': SPRITE_COLORS_16BIT.TRANSPARENT,
    'S': SPRITE_COLORS_16BIT.DOWNTOWN_STEEL,
    'D': SPRITE_COLORS_16BIT.DOWNTOWN_STEEL_DARK,
    'G': SPRITE_COLORS_16BIT.DOWNTOWN_GLASS,
    'B': SPRITE_COLORS_16BIT.DOWNTOWN_GLASS_DARK,
    'L': SPRITE_COLORS_16BIT.DOWNTOWN_GLASS_LIGHT
  },
  warehouse: {
    'R': SPRITE_COLORS_16BIT.WAREHOUSE_BRICK,
    'B': SPRITE_COLORS_16BIT.WAREHOUSE_BRICK_DARK,
    'L': SPRITE_COLORS_16BIT.WAREHOUSE_BRICK_LIGHT,
    'D': SPRITE_COLORS_16BIT.WAREHOUSE_RUST_DARK,
    'M': SPRITE_COLORS_16BIT.WAREHOUSE_METAL,
    'W': SPRITE_COLORS_16BIT.GRAY_DARK
  },
  college: {
    '.': SPRITE_COLORS_16BIT.TRANSPARENT,
    'S': SPRITE_COLORS_16BIT.COLLEGE_STONE,
    'D': SPRITE_COLORS_16BIT.COLLEGE_STONE_DARK,
    'L': SPRITE_COLORS_16BIT.COLLEGE_STONE_LIGHT,
    'I': SPRITE_COLORS_16BIT.COLLEGE_IVY,
    'G': SPRITE_COLORS_16BIT.COLLEGE_IVY_DARK,
    'W': SPRITE_COLORS_16BIT.WINDOW_BLUE
  },
  residential: {
    '.': SPRITE_COLORS_16BIT.TRANSPARENT,
    'S': SPRITE_COLORS_16BIT.RESIDENTIAL_SIDING,
    'D': SPRITE_COLORS_16BIT.RESIDENTIAL_SIDING_DARK,
    'L': SPRITE_COLORS_16BIT.RESIDENTIAL_SIDING_LIGHT,
    'R': SPRITE_COLORS_16BIT.RESIDENTIAL_ROOF,
    'W': SPRITE_COLORS_16BIT.WINDOW_YELLOW,
    'G': SPRITE_COLORS_16BIT.GRASS_GREEN
  },
  arts: {
    '.': SPRITE_COLORS_16BIT.TRANSPARENT,
    'P': SPRITE_COLORS_16BIT.ARTS_PURPLE,
    'D': SPRITE_COLORS_16BIT.ARTS_PURPLE_DARK,
    'T': SPRITE_COLORS_16BIT.ARTS_TEAL,
    'C': SPRITE_COLORS_16BIT.ARTS_PINK,
    'W': SPRITE_COLORS_16BIT.WINDOW_BLUE
  }
};

// Venue sprite - Music club with neon sign
const VENUE_PATTERN_16BIT = [
  '................',
  '..PPPPPPPPPPPP..',
  '.PPCCCCCCCCCCPP.',
  '.PCNCNCNCNCNCCP.',
  '.PCCCCCCCCCCCCP.',
  '.PCPPPPPPPPPPCP.',
  '.PCPWWPPWWPPCP.',
  '.PCPDDPPDDDPCP.',
  '.PCPWWPPWWPPCP.',
  '.PCPPPPPPPPPPCP.',
  '.PCPWWPPWWPPCP.',
  '.PCPDDPPDDDPCP.',
  '.PCPPDDDDDDPPCP.',
  '.PCPPDMMMMDPPCP.',
  '.PPPPPPPPPPPPPP.',
  'DDDDDDDDDDDDDDDD'
];

const VENUE_COLORS_16BIT = {
  '.': SPRITE_COLORS_16BIT.TRANSPARENT,
  'P': SPRITE_COLORS_16BIT.GRAY_DARK,
  'D': SPRITE_COLORS_16BIT.GRAY_DARKER,
  'C': SPRITE_COLORS_16BIT.NEON_PURPLE,
  'N': SPRITE_COLORS_16BIT.NEON_CYAN,
  'W': SPRITE_COLORS_16BIT.WINDOW_DARK,
  'M': SPRITE_COLORS_16BIT.BLACK
};

// Workplace - Office building
const WORKPLACE_PATTERN_16BIT = [
  '....BBBBBBBB....',
  '...BBBBBBBBBB...',
  '..BBBBBBBBBBBB..',
  '..BWWBWWBWWBWB..',
  '..BSSBSSBSSBSB..',
  '..BWWBWWBWWBWB..',
  '..BBBBBBBBBBBB..',
  '..BWWBWWBWWBWB..',
  '..BSSBSSBSSBSB..',
  '..BWWBWWBWWBWB..',
  '..BBBBBBBBBBBB..',
  '..BWWBWWBWWBWB..',
  '..BSSBSSBSSBSB..',
  '..BBBBDDDDBBBB..',
  '..BBBBBBBBBBBB..',
  '................'
];

const WORKPLACE_COLORS_16BIT = {
  '.': SPRITE_COLORS_16BIT.TRANSPARENT,
  'B': SPRITE_COLORS_16BIT.DOWNTOWN_STEEL,
  'S': SPRITE_COLORS_16BIT.DOWNTOWN_GLASS,
  'W': SPRITE_COLORS_16BIT.WINDOW_BLUE,
  'D': SPRITE_COLORS_16BIT.GRAY_DARKEST
};

// Park with trees and paths
const PARK_PATTERN_16BIT = [
  'GGGGGGGGGGGGGGGG',
  'GGTTGGGGGGTTGGGG',
  'GTTTGGGGGGTTTGGG',
  'GTTTTGGGGTTTTTGG',
  'GGBTGGGGGGGTBGGG',
  'GGGGPPPPPPGGGGGG',
  'GGGGPPPPPPGGGGGG',
  'GGGGGGGGGGGGGGGG',
  'GGTTGGGGGGTTGGGG',
  'GTTTGGGGGGTTTGGG',
  'GTTTTGGGGTTTTTGG',
  'GGBTGGGGGGGTBGGG',
  'GGGGPPPPPPGGGGGG',
  'GGGGPPPPPPGGGGGG',
  'GGGGGGGGGGGGGGGG',
  'GGGGGGGGGGGGGGGG'
];

const PARK_COLORS_16BIT = {
  'G': SPRITE_COLORS_16BIT.GRASS_GREEN,
  'D': SPRITE_COLORS_16BIT.GRASS_DARK,
  'T': SPRITE_COLORS_16BIT.TREE_GREEN,
  'B': SPRITE_COLORS_16BIT.TREE_TRUNK,
  'P': SPRITE_COLORS_16BIT.SIDEWALK
};

// Street patterns - simpler and cleaner
const STREET_PATTERNS_16BIT = {
  horizontal: [
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'AALLLLLLLLLLLLAA',
    'AALLLLLLLLLLLLAA',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDD'
  ],
  vertical: [
    'DDDDDDDDDDDDDDDD',
    'DDDDDDLLDDDDDDDD',
    'DDDDDDLLDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDLLDDDDDDDD',
    'DDDDDDLLDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDLLDDDDDDDD',
    'DDDDDDLLDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDLLDDDDDDDD',
    'DDDDDDLLDDDDDDDD',
    'DDDDDDDDDDDDDDDD'
  ],
  intersection: [
    'DDDDDDDAADDDDDDD',
    'DDDDDDDAADDDDDDD',
    'DDDDDDDAADDDDDDD',
    'DDDDDDDAADDDDDDD',
    'DDDDDDDAADDDDDDD',
    'DDDDDDDAADDDDDDD',
    'DDDDDDDAADDDDDDD',
    'AAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAA',
    'DDDDDDDAADDDDDDD',
    'DDDDDDDAADDDDDDD',
    'DDDDDDDAADDDDDDD',
    'DDDDDDDAADDDDDDD',
    'DDDDDDDAADDDDDDD',
    'DDDDDDDAADDDDDDD',
    'DDDDDDDAADDDDDDD'
  ]
};

const STREET_COLORS_16BIT = {
  'D': SPRITE_COLORS_16BIT.ASPHALT_DARK,
  'A': SPRITE_COLORS_16BIT.ASPHALT,
  'L': SPRITE_COLORS_16BIT.STREET_LINE,
  'S': SPRITE_COLORS_16BIT.SIDEWALK
};

// Convert pattern to sprite data
function createSprite(pattern: string[], colors: Record<string, string>): SpriteData {
  return pattern.map(row => 
    row.split('').map(char => colors[char] || SPRITE_COLORS_16BIT.TRANSPARENT)
  );
}

// Create sprite cache
export const SPRITES_16BIT = {
  // Buildings
  building_downtown: createSprite(BUILDING_PATTERNS_16BIT.downtown, BUILDING_COLORS_16BIT.downtown),
  building_warehouse: createSprite(BUILDING_PATTERNS_16BIT.warehouse, BUILDING_COLORS_16BIT.warehouse),
  building_college: createSprite(BUILDING_PATTERNS_16BIT.college, BUILDING_COLORS_16BIT.college),
  building_residential: createSprite(BUILDING_PATTERNS_16BIT.residential, BUILDING_COLORS_16BIT.residential),
  building_arts: createSprite(BUILDING_PATTERNS_16BIT.arts, BUILDING_COLORS_16BIT.arts),
  
  // Streets
  street_horizontal: createSprite(STREET_PATTERNS_16BIT.horizontal, STREET_COLORS_16BIT),
  street_vertical: createSprite(STREET_PATTERNS_16BIT.vertical, STREET_COLORS_16BIT),
  street_intersection: createSprite(STREET_PATTERNS_16BIT.intersection, STREET_COLORS_16BIT),
  
  // Special
  venue_inactive: createSprite(VENUE_PATTERN_16BIT, VENUE_COLORS_16BIT),
  venue_active: createSprite(VENUE_PATTERN_16BIT, {
    ...VENUE_COLORS_16BIT,
    'C': SPRITE_COLORS_16BIT.NEON_PINK,
    'N': SPRITE_COLORS_16BIT.NEON_PURPLE,
    'W': SPRITE_COLORS_16BIT.WINDOW_YELLOW
  }),
  workplace: createSprite(WORKPLACE_PATTERN_16BIT, WORKPLACE_COLORS_16BIT),
  park: createSprite(PARK_PATTERN_16BIT, PARK_COLORS_16BIT)
};