#!/usr/bin/env node
/**
 * packSprites — pack individual sprite PNGs into one atlas + a typed coords map.
 *
 * Workflow: drop hand-drawn / AI-generated / palette-snapped PNGs into
 * `art/sprites/` (one sprite per file, transparent background — subfolders OK).
 * Run `npm run pack:sprites`. This emits:
 *
 *   public/assets/sprites/generated/atlas.png  — the packed sheet
 *   src/components/map/generatedAtlas.ts        — { name: {x,y,w,h} } + src path
 *
 * No more measuring rects by hand (cf. the hand-authored townAtlas.ts): name the
 * file `town/amp.png`, get `GENERATED_SPRITES.town_amp = {x,y,w,h}` for free.
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { packAsync } from 'free-tex-packer-core';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC_DIR = path.join(ROOT, 'art/sprites');
const OUT_PNG_DIR = path.join(ROOT, 'public/assets/sprites/generated');
const OUT_TS = path.join(ROOT, 'src/components/map/generatedAtlas.ts');

const spriteKey = (p) =>
  p.replace(/\.png$/i, '').replace(/[/\-\s.]+/g, '_').replace(/^_+|_+$/g, '');

async function collectPngs(dir, base = dir) {
  const out = [];
  if (!existsSync(dir)) return out;
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await collectPngs(full, base)));
    else if (entry.name.toLowerCase().endsWith('.png')) {
      out.push({
        path: path.relative(base, full).replace(/\\/g, '/'),
        contents: await readFile(full),
      });
    }
  }
  return out;
}

function emitModule(sprites) {
  const body = sprites
    .map(([name, r]) => `  ${name}: { x: ${r.x}, y: ${r.y}, w: ${r.w}, h: ${r.h} },`)
    .join('\n');
  return `// AUTO-GENERATED by scripts/packSprites.mjs — do not edit by hand.
// Source sprites live in art/sprites/; run \`npm run pack:sprites\` to regenerate.
export interface GenRect { x: number; y: number; w: number; h: number; }

/** Path to the packed atlas (served from /public). */
export const GENERATED_ATLAS_SRC = '/assets/sprites/generated/atlas.png';

/** Sprite rects within the generated atlas, keyed by source filename. */
export const GENERATED_SPRITES = {
${body}
} as const;

export type GeneratedSpriteName = keyof typeof GENERATED_SPRITES;
`;
}

const images = await collectPngs(SRC_DIR);

await mkdir(path.dirname(OUT_TS), { recursive: true });

if (images.length === 0) {
  console.log('[pack-sprites] No PNGs in art/sprites/. Add sprites and re-run.');
  await writeFile(OUT_TS, emitModule([]));
  process.exit(0);
}

const files = await packAsync(images, {
  textureName: 'atlas',
  width: 2048,
  height: 2048,
  fixedSize: false,
  powerOfTwo: false,
  padding: 1,
  allowRotation: false,
  allowTrim: false,
  detectIdentical: true,
  removeFileExtension: true,
  prependFolderName: true,
  exporter: 'JsonHash',
});

const png = files.find((f) => f.name.endsWith('.png'));
const json = files.find((f) => f.name.endsWith('.json'));
if (!png || !json) throw new Error('[pack-sprites] packer did not return png + json');

const frames = JSON.parse(json.buffer.toString('utf8')).frames;
const sprites = Object.entries(frames)
  .map(([name, f]) => [spriteKey(name), { x: f.frame.x, y: f.frame.y, w: f.frame.w, h: f.frame.h }])
  .sort((a, b) => a[0].localeCompare(b[0]));

await mkdir(OUT_PNG_DIR, { recursive: true });
await writeFile(path.join(OUT_PNG_DIR, 'atlas.png'), png.buffer);
await writeFile(OUT_TS, emitModule(sprites));

console.log(
  `[pack-sprites] packed ${sprites.length} sprite(s) → ${path.relative(ROOT, OUT_PNG_DIR)}/atlas.png + ${path.relative(ROOT, OUT_TS)}`,
);
