// AUTO-GENERATED by scripts/packSprites.mjs — do not edit by hand.
// Source sprites live in art/sprites/; run `npm run pack:sprites` to regenerate.
export interface GenRect { x: number; y: number; w: number; h: number; }

/** Path to the packed atlas (served from /public). */
export const GENERATED_ATLAS_SRC = '/assets/sprites/generated/atlas.png';

/** Sprite rects within the generated atlas, keyed by source filename. */
export const GENERATED_SPRITES = {
  demo_amp: { x: 1, y: 1, w: 22, h: 18 },
  demo_diamond: { x: 1, y: 21, w: 16, h: 16 },
  demo_orb: { x: 47, y: 1, w: 16, h: 16 },
  demo_ring: { x: 25, y: 1, w: 20, h: 20 },
} as const;

export type GeneratedSpriteName = keyof typeof GENERATED_SPRITES;
