// AUTO-GENERATED by scripts/packSprites.mjs — do not edit by hand.
// Source sprites live in art/sprites/; run `npm run pack:sprites` to regenerate.
export interface GenRect { x: number; y: number; w: number; h: number; }

/** Path to the packed atlas (served from /public). */
export const GENERATED_ATLAS_SRC = '/assets/sprites/generated/atlas.png';

/** Sprite rects within the generated atlas, keyed by source filename. */
export const GENERATED_SPRITES = {
  town_cable_coil: { x: 73, y: 21, w: 14, h: 8 },
  town_crate_stack: { x: 73, y: 1, w: 16, h: 18 },
  town_floor_amp: { x: 109, y: 1, w: 16, h: 14 },
  town_flyer_pole: { x: 127, y: 1, w: 14, h: 26 },
  town_flyer_pole_b: { x: 109, y: 17, w: 14, h: 26 },
  town_guitar_case: { x: 51, y: 23, w: 12, h: 20 },
  town_keg_cooler: { x: 51, y: 45, w: 12, h: 16 },
  town_mic_stand: { x: 89, y: 29, w: 12, h: 24 },
  town_pa_speaker_stack: { x: 1, y: 17, w: 16, h: 26 },
  town_poster_wall: { x: 53, y: 1, w: 18, h: 20 },
  town_road_case: { x: 31, y: 15, w: 18, h: 14 },
  town_sandwich_board: { x: 91, y: 1, w: 16, h: 18 },
  town_stage_riser: { x: 31, y: 1, w: 20, h: 12 },
  town_string_lights: { x: 1, y: 1, w: 28, h: 14 },
} as const;

export type GeneratedSpriteName = keyof typeof GENERATED_SPRITES;
